SmartHouseMVC/Models/WebReader.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SmartHouseDll;

namespace SmartHouseMVC.Models
{
    public class WebReader : Storage, IReader
    {
        public WebReader(House home) : base(home)
        {
        }

        public void Read()
        {
            
        }

        public void Help(RemoteControl remote, string message)
        {
            
        }
    }
}

SmartHouseMVC/Controllers/DeviceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SmartHouseDll;

namespace SmartHouseMVC.Controllers
{
    public class DeviceController : Controller
    {
        private House house;
        private string view;


        public ActionResult Command(string room, string device, string command)
        {
            house = Session["home"] as House;

            if (command.Contains("_plus"))
                command = command.Replace("_plus", "+");

            house.Remote.Reader.RoomData = room;
            house.Remote.Reader.DeviceData = device;
            house.Remote.Reader.CommandData = command;

            house.Remote.PushButton();

            Session["home"] = house;
            SaveHouse();
            GetView();

            return View(view, house);
        }
        public ActionResult LigthSelect(string room, string device, string command)
        {
            house = Session["home"] as House;

            ILight light = house.GetDevice(room, device) as ILight;
            if (light != null)
            {
                light.Brightness = (LightsState)Enum.Parse(typeof(LightsState), command);
                
            }

            house.Remote.PushButton();

            Session["home"] = house;
            SaveHouse();
            GetView();
            return View(view, house);
        }
 
        
        private void GetView()
        {
            if (Request.Cookies.Get("view") == null)
            {
                view = "~/Views/Home/Index.cshtml";
            }
            else
            {
                view = Request.Cookies.Get("view").Value;
            }
        }
        private void SaveHouse()
        {
            if (house != null)
            {
                SerDesHouse.Save(house);
            }
        }

	}
}

SmartHouseMVC/Controllers/HomeController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SmartHouseDll;

namespace SmartHouseMVC.Controllers
{
    public class HomeController : Controller
    {
        private House house;
        private string view;


        public ActionResult Index()
        {
            house = Session["home"] as House;

            Response.Cookies.Add(new HttpCookie("view", "~/Views/Home/Index.cshtml"));
            return View(house);
        }

         public ActionResult AddTools()
        {
            house = Session["home"] as House;

            Response.Cookies.Add(new HttpCookie("view", "~/Views/Home/AddTools.cshtml"));
            return View(house);
        }
         public ActionResult AddRoom()
         {
             house = Session["home"] as House;
             GetView();

             house.Remote.Reader.RoomData = Request.Params["addRoom"];
             house.Remote.Reader.CommandData = "addRom";
             house.Remote.PushButton();

             SaveHouse();
             return View(view, house);
         }      
         public ActionResult AddDevice()
         {
             house = Session["home"] as House;
             GetView();

             house.Remote.Reader.RoomData = Request.Params["list_room"];
             house.Remote.Reader.DeviceData = Request.Params["addDevice"];

             house.Remote.Reader.CommandData = house.Remote.Commands.Values.
                 Where(c => c.Inform.Contains("Добавить " + Request.Params["list_device"])).
                 Select(c=>c.Name).First();

             house.Remote.PushButton();

             SaveHouse();
             return View(view, house);
         }
           

        public ActionResult DelTools()
        {
            house = Session["home"] as House;         

            Response.Cookies.Add(new HttpCookie("view", "~/Views/Home/DelTools.cshtml"));
            return View(house);
        }
        public ActionResult DelRoom()
        {
            house = Session["home"] as House;
            GetView();

            house.Remote.Reader.RoomData = Request.Params["list_room"];
            house.Remote.Reader.CommandData = "delRom";
            house.Remote.PushButton();

            SaveHouse();
            return View(view, house);
        }
        public ActionResult DelDevice()
        {
            house = Session["home"] as House;
            GetView();

            house.Remote.Reader.RoomData = Request.Params["list_room_device"];
            house.Remote.Reader.DeviceData = Request.Params["list_device"];

            house.Remote.Reader.CommandData = "delDev";

            house.Remote.PushButton();

            SaveHouse();
            return View(view, house);
        }
        public ActionResult Devices(string id)
        {
            house = Session["home"] as House;
            if (house == null)
                return Redirect("/Home/Index");


            ViewBag.RoomName = house.GetRoom(id).Name;

            ViewBag.Devices = new SelectList(house.GetRoom(id).Devices.Values, "Name", "Name");


           GetView();

            return View(view, house);
        }

        public ActionResult RedactTools()
        {
            house = Session["home"] as House;

            Response.Cookies.Add(new HttpCookie("view", "~/Views/Home/RedactTools.cshtml"));
            return View(house);
        }
        public ActionResult RedactRoom()
        {
            house = Session["home"] as House;
            GetView();

            house.ChangeNameRoom(Request.Params["list_room"], Request.Params["redactRoom"]);

            SaveHouse();
            return View(view, house);
        }
        public ActionResult RedactDevice()
        {
            house = Session["home"] as House;
            GetView();

            house.ChangeNameDevice(Request.Params["list_room_device"], Request.Params["list_device"], Request.Params["redactDevice"]);

            SaveHouse();
            return View(view, house);
        }

        private void GetView()
        { 
            if (Request.Cookies.Get("view") == null)
            {
                view = "~/Views/Home/Index.cshtml";
            }
            else
            {
                view = Request.Cookies.Get("view").Value;
            }
        }
        private void SaveHouse()
        {
            if (house != null)
            {
                SerDesHouse.Save(house);
            }
        }
    }
}

SmartHouseMVC/Views/Home/AddTools.cshtml
@using System.Collections
@model SmartHouseDll.House



@using (Html.BeginForm("AddRoom", "Home", FormMethod.Post))
{
    <div class="panAdd">
        <fieldset>
            <legend>
                Добавить комнату
            </legend>
            @Html.TextBox("addRoom", "", new { placeholder = "Имя комнаты" })
            <br />
            <br />
            <input type="submit" value="Добавить" />
        </fieldset>
    </div>
}

@using (Html.BeginForm("AddDevice", "Home", FormMethod.Post))
{
    <div class="panAdd">
        <fieldset>
            <legend>
                Добавить устройство
            </legend>
            @Html.DropDownList("list_room", new SelectList(Model.Rooms.Values, "Name", "Name"))

            @{
                var devices = Model.Remote.Commands.Values.
                    Where(c => c.Name.StartsWith("add") & !c.Inform.Contains("комнату")).
                    Select(c => c.Inform.Replace("Добавить ", string.Empty));
            }

            @Html.DropDownList("list_device", new SelectList(devices.ToList()))
            <br />
            <br />
            @Html.TextBox("addDevice", "", new { placeholder = "Имя устройства" })
            <br />
            <br />
            <input type="submit" value="Добавить" />
        </fieldset>
    </div>
}

SmartHouseMVC/Views/Home/DelTools.cshtml
@using System.Collections
@model SmartHouseDll.House



@using (Html.BeginForm("DelRoom", "Home", FormMethod.Post))
{
    <div class="panAdd">
        <fieldset>
            <legend>
                Удалить комнату
            </legend>
            @Html.DropDownList("list_room", new SelectList(Model.Rooms.Values, "Name", "Name"))            
            <br />
            <br />
            <input type="submit" value="Удалить" />
        </fieldset>
    </div>
}

@using (Html.BeginForm("DelDevice", "Home", FormMethod.Post))
{
    <div class="panAdd">
        <fieldset>
            <legend>
                Удалить устройство
            </legend>
            @Html.DropDownList("list_room_device", new SelectList(Model.Rooms.Values, "Name", "Name", ViewBag.RoomName), new { onchange = "changeItemList1('list_room_device')" }))

            @{
                if (ViewBag.Devices == null)
                {
                    ViewBag.Devices = new SelectList(Model.Rooms.Values.First().Devices.Values, "Name", "Name");
                }
            }
            @Html.DropDownList("list_device", ViewBag.Devices as SelectList);
            <br />
            <br />
            <input type="submit" value="Удалить" />
        </fieldset>
    </div>
}

SmartHouseMVC/Views/Home/Index.cshtml
@model SmartHouseDll.House

SmartHouseMVC/Views/Home/RedactTools.cshtml
@model SmartHouseDll.House

@using (Html.BeginForm("RedactRoom", "Home", FormMethod.Post))
{
    <div class="panAdd">
        <fieldset>
            <legend>
                Редактировать комнату
            </legend>
            @Html.DropDownList("list_room", new SelectList(Model.Rooms.Values, "Name", "Name"))
            <br />
            <br />
            @Html.TextBox("redactRoom", "", new { placeholder = "Новое имя комнаты" })
            <br />
            <br />
            <input type="submit" value="Редактировать" />
        </fieldset>
    </div>
}

@using (Html.BeginForm("RedactDevice", "Home", FormMethod.Post))
{
    <div class="panAdd">
        <fieldset>
            <legend>
                Редактировать устройство
            </legend>
            @Html.DropDownList("list_room_device", new SelectList(Model.Rooms.Values, "Name", "Name", ViewBag.RoomName), new { onchange = "changeItemList1('list_room_device')" }))
            
            @{
                if (ViewBag.Devices == null)
                {
                    ViewBag.Devices = new SelectList(Model.Rooms.Values.First().Devices.Values, "Name", "Name");
                }               
            }
            @Html.DropDownList("list_device", ViewBag.Devices as SelectList);
            <br />
            <br />
            @Html.TextBox("redactDevice", "", new { placeholder = "Новое имя устройства" })
            <br />
            <br />
            <input type="submit" value="Редактировать" />
        </fieldset>
    </div>
}

SmartHouseMVC/Views/Shared/Device/ClimatControl.cshtml
@using SmartHouseDll
@model SmartHouseDll.ClimatControl

<div class="panLamp">
    <span class="nameDevice">@Model.Name</span>
    <img class="imgBt" src="~/Content/Images/hot.png" />
    @{
        ViewBag.device = Model.NameId;
        ViewBag.temper = Model.Temperature;

        Html.RenderPartial("Device/OnOff");
    }
    <span class="labelTemper">@Model.SensorTemperat.CurrentTemperature</span>

    <a href="/Device/Command/@ViewBag.room/@ViewBag.device/cl-Auto">
        @if (Model.Auto)
        {
            <img src="~/Content/Images/AutoOn.png" class="imgBt" />
        }
        else
        {
            <img src="~/Content/Images/AutoOff.png" class="imgBt" />
        }
    </a>
    <a href="/Device/Command/@ViewBag.room/@ViewBag.device/cl-heat">

        @if (Model.Heat.State == StateOnOff.Off)
        {
            <img src="~/Content/Images/hot1.png" class="imgBt" />
        }
        else
        {
            <img src="~/Content/Images/hot1.png" class="imgBt imgColor" />
        }

    </a>
    <a href="/Device/Command/@ViewBag.room/@ViewBag.device/cl-cond">
        @if (Model.Cond.State == StateOnOff.Off)
        {
            <img src="~/Content/Images/ice2.png" class="imgBt" />
        }
        else
        {
            <img src="~/Content/Images/ice2.png" class="imgBt imgColor" />
        }
    </a>

    @Html.Partial("Device/Temper")
</div>

SmartHouseMVC/Views/Shared/Device/Lamp.cshtml
@using SmartHouseDll
@model SmartHouseDll.Lamp



<div class="panLamp">
    <span class="nameDevice">@Model.Name</span>

    @if (Model.State == StateOnOff.Off)
    {
        <img src="~/Content/Images/lightbulb.png" class="imgBt" />
    <a href="/Device/Command/@ViewBag.room/@Model.NameId/on">
        <img src="~/Content/Images/control_power.png" class="imgBt" />
    </a>
    }
    else
    {
        <img src="~/Content/Images/lightbulb_on.png" class="imgBt" />
    <a href="/Device/Command/@ViewBag.room/@Model.NameId/off">
        <img src="~/Content/Images/control_power_blue.png" class="imgBt" />
    </a>
    }

    @{
        ViewBag.device = Model.NameId;
        ViewBag.ligth = Model.Brightness;
        Html.RenderPartial("Device/Light");
    }

</div>

SmartHouseMVC/Views/Shared/Device/Light.cshtml
@using SmartHouseDll

@{
    string id = "enumLight_" + ViewBag.room + "_" + ViewBag.device;
}
<div class="panLight">
    <img class="imgBt" src="~/Content/Images/litgh.png" />
    <select id=@id class="enumLight" onchange="changeItemList('@id', '/Device/LigthSelect/', '@ViewBag.room', '@ViewBag.device')">
        @{
            //LightsState lightsState = (LightsState)ViewBag.ligth;
            if (ViewBag.ligth == LightsState.Low)
            {
                <option value=@LightsState.Low selected="selected">Слабая</option>
            }
            else
            {
                <option value=@LightsState.Low>Слабая</option>
            }

            if (ViewBag.ligth == LightsState.Medium)
            {
                <option value=@LightsState.Medium selected="selected">Средняя</option>
            }
            else
            {
                <option value=@LightsState.Medium>Средняя</option>
            }

            if (ViewBag.ligth == LightsState.High)
            {
                <option value=@LightsState.High selected="selected">Высокая</option>
            }
            else
            {
                <option value=@LightsState.High>Высокая</option>
            }
        }
    </select>
</div>

SmartHouseMVC/Views/Shared/Device/OnOff.cshtml
@using SmartHouseDll
@model SmartHouseDll.Device
           
@if (Model.State == StateOnOff.Off)
{
    <a href="/Device/Command/@ViewBag.room/@Model.NameId/on">
        <img src="~/Content/Images/control_power.png" class="imgBt" />
    </a>
}
else
{
    <a href="/Device/Command/@ViewBag.room/@Model.NameId/off">
        <img src="~/Content/Images/control_power_blue.png" class="imgBt" />
    </a>
}

SmartHouseMVC/Views/Shared/Device/Room.cshtml
@using SmartHouseDll
@model SmartHouseDll.Room

<div>
    <span class="labelRoom">@Model.Name</span>
    @{
        foreach (Device device in Model.Devices.Values.OrderBy(c=>c.GetType().FullName))
        {
            ViewBag.room = Model.NameId;

            if (device is Lamp)
            {
                Html.RenderPartial("Device/Lamp", device as Lamp);
            }
            if (device is ClimatControl)
            {
                Html.RenderPartial("Device/ClimatControl", device as ClimatControl);
            }
            if (device is Tv)
            {
                Html.RenderPartial("Device/Tv", device as Tv);
            }
        }
    }      

</div>

SmartHouseMVC/Views/Shared/Device/Temper.cshtml
<div class="panTemper">
    <img class="imgBt" src="~/Content/Images/Temper1.png" />

    <a href="/Device/Command/@ViewBag.room/@ViewBag.device/t_plus">
        <img src="~/Content/Images/up_plus.png" class="imgBt" />
    </a>

    <span class="labelTemperat">@ViewBag.temper</span>

    <a href="/Device/Command/@ViewBag.room/@ViewBag.device/t-">
        <img src="~/Content/Images/down_minus.png" class="imgBt imgBtV" />
    </a>
</div>

SmartHouseMVC/Views/Shared/Device/Tv.cshtml
@using SmartHouseDll
@model SmartHouseDll.Tv

<div class="panLamp">
    <span class="nameDevice">@Model.Name</span>

    @if (Model.State == StateOnOff.Off)
    {       
        <img src="~/Content/Images/television.png" class="imgBt" />
    }
    else
    {
        <img src="~/Content/Images/932273044.gif" class="imgBt" />
    }

    @{
        ViewBag.device = Model.NameId;
        ViewBag.vol = Model.Volume;
        ViewBag.ligth = Model.Brightness;

        Html.RenderPartial("Device/OnOff");
        Html.RenderPartial("Device/Light");
        Html.RenderPartial("Device/Volume");
    }


</div>

SmartHouseMVC/Views/Shared/Device/Volume.cshtml
<div class="panVolume">
    <img class="imgBt" src="~/Content/Images/sound_low.png"/>

    <a href="/Device/Command/@ViewBag.room/@ViewBag.device/vol_plus">
        <img src="~/Content/Images/up_plus.png" class="imgBt" />
    </a>

    <span class="labelVolume">@ViewBag.vol</span>

    <a href="/Device/Command/@ViewBag.room/@ViewBag.device/vol-">
        <img src="~/Content/Images/down_minus.png" class="imgBt imgBtV" />
    </a>
</div>

SmartHouseMVC/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
@using SmartHouseDll
@using SmartHouseMVC.Models

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SmartHouse</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/MyStyle.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/MyScript.js"></script>
</head>
<body>

    <div class="container">
        <div class="row">
            <div class="col-md-5 ml-45">
                <form id="form1">
                    <div id="panHouse">
                        @{
                            House house = (House)Session["home"];

                            Session["room"] = house.Rooms.First().Key;

                            //var lamps = house.Rooms.Values.First().Devices.Values.Where(c => c is Lamp);
                            //foreach (Lamp lamp in lamps)
                            //{
                            //    Html.RenderPartial("Device/Lamp", lamp);
                            //    Session["device"] = lamp.NameId;
                            //    //Html.Action("Lamp", "Device");
                            //}

                            foreach (Room room in house.Rooms.Values)
                            {
                                Html.RenderPartial("Device/Room", room);
                            }
                        }


                    </div>
                </form>
                <br />
            </div>
            <div class="col-md-3 headerSmart">
                <div id="Panel1">
                    <img src="~/Content/Images/12.png" style="margin-top: 30%; margin-left: -25px" />
                    <img src="~/Content/Images/фон3.png" style="margin-top: 50px; margin-left: -55px; width: 160%" />
                </div>
                <br />
            </div>
            <div class="col-md-4 tools">
                <div class="navbar">
                    <div class="container">
                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">
                                <li class="li_menu">@Html.ActionLink("Домой", "Index", "Home")</li>
                                <li class="li_menu">@Html.ActionLink("Редактировать", "RedactTools", "Home")</li>
                                <li class="li_menu">@Html.ActionLink("Добавить", "AddTools", "Home")</li>
                                <li class="li_menu">@Html.ActionLink("Удалить", "DelTools", "Home")</li>
                            </ul>
                        </div>
                    </div>
                </div>
                @RenderBody()
            </div>
        </div>
    </div>
    <div>
    </div>
</body>
</html>